app/Http/routes.php
<?php

/*
API endpoints
*/
Route::get('t','DummyController@order'); 
Route::get('no-permissions',function(){
    return view('nopermissions');
}


); 
Route::group(['prefix'=>'api/v1','as'=>'Api/v1::'],function() {      
    Route::post('auth','Api\AuthController@auth');
    Route::post('sync','Api\SyncController@index');
    Route::post('push','Api\PushController@push');
    Route::get('reports','Api\ReportControllerer@index'); 
    Route::post('report','Api\ReportControllerer@generate'); 

    Route::resource('orders','Api\OrderController');
    Route::resource('logs','Api\LogController');
});

/*
Web endpoints
*/
Route::group(['middleware' => 'web'], function () {
    Route::auth();

    Route::get('/', 'OrderController@index');
    Route::get('orders/{id}/confirmation','OrderController@confirmation');
    Route::get('orders/{id}/decline','OrderController@decline');
    Route::resource('/resellers','ResellerController');
    Route::resource('/resellers/groups','ResellersGroupController');
    Route::resource('/promotions','PromotionController');
    Route::resource('/packages','PromotionController');
    Route::resource('/users','UserController');
    Route::resource('/orders','OrderController');
    Route::resource('/reports','ReportController');
    Route::post('reports/export','ReportController@export');

    Route::get('orders','OrderController@create');
    Route::post('orders','OrderController@store');
});

Route::get('/check-api-orders/{user}', function($user){
	

	
	$todayOrders = App\Order::with(['globalReseller', 'details.pharmacy', 'details.chain'])
                        ->madeBy($user)->fromToday()->get();
      
        $pendingOrders = App\Order::with(['details', 'details.pharmacy', 'details.chain'])
                        ->madeBy($user)->notConfirmed()->get();
        
        return response()->json([
                'today_orders' => (new App\Http\Transformers\OrderTransformer)->transformCollection($todayOrders->toArray()),
                'proccessing_orders' => (new App\Http\Transformers\PendingOrderTransformer)->transformCollection($pendingOrders->toArray()),
            ], 200
        );
	
});

Route::get('/check-api-pharms/{cwid}', function($cwid){
	
	
	$chains = App\ChainViewModel::with('pharmacies')->get();

        $ownedPharmacies = App\PharmacyViewModel::where('owner_id', $cwid)->get();
        $ownedPharmsIds=$ownedPharmacies->map(function($pharm){
            return $pharm->id;
        });

        $chainPharmacies = App\PharmacyViewModel::whereNotIn('id', $ownedPharmsIds)->where('chain_id', '!=', NULL)->get();
        $pharmacies=$ownedPharmacies->merge($chainPharmacies);
		
	return $pharmacies;
	
	
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

    use HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email','cwid','token', 'password','is_active','phone'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    
    protected $hidden = [
        'password', 'remember_token',
    ];

     public function resellers()
    {
        return $this->belongsToMany('App\Reseller');
    }

    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
     public function scopeActive($query)
    {
        return $query->where('is_active',1);
    }
    public function isActive()
    {
        return $this->is_active;
    }
     
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\CreateUserRequest;
use App\User;
use App\Role;

class UserController extends Controller
{
    public function index() {
    	$users = User::all();
    	return view('users.index',compact('users'));
    }

    public function create() {
    	$roles = Role::all();
    	return view('users.create',compact('roles'));
    }

    public function store(CreateUserRequest $request) {
    	$user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'cwid' => $request->cwid,
            'token' => uniqid('ios'),
            'password' => $request->password,
        ]);
        $user->assignRole($request->role_name);
        
        return redirect()->to('users');	
    }

    public function edit(User $user) 
    {
        $user->load('roles');
        $roles = Role::all();

        return view('users.show', compact('user', 'roles'));
    }

    public function update(User $user, Request $request)
    {
        $this->validate($request, ['password' => 'min:4|confirmed']);

        $values = array_filter($request->input());
        if (!$request->is_active) {
            $values['is_active']=0;
        }

        $user->update($values);
        $user->assignRole($values['role_name']);

        return redirect('users');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{ trans('users.create') }}</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/users') }}">
                        {!! csrf_field() !!}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.name') }}</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" value="{{ old('name') }}">
                                @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.email') }}</label>
                            <div class="col-md-6">
                                <input type="email" class="form-control" name="email" value="{{ old('email') }}">
                                @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.cwid') }}</label>
                            <div class="col-md-6">
                                <input type="cwid" class="form-control" name="cwid" value="{{ old('cwid') }}">
                            </div>
                            </div>
                             <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.phone') }}</label>
                            <div class="col-md-6">
                                <input type="phone" class="form-control" name="phone" value="{{ old('phone') }}">
                            </div>
                            </div>
                            <div class="form-group{{ $errors->has('role_name') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">{{ trans('users.role') }}</label>
                                <div class="col-md-4">
                                    <select name="role_name" class="form-control">
                                        
                                        @foreach ($roles as $role)
                                        <option value="{{$role->name}}">{{$role->label}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    
                                    
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                                <label class="col-md-4 control-label">{{ trans('users.password') }}</label>
                                <div class="col-md-6">
                                    <input type="text" class="form-control" id="password" name="password"> <a class="btn btn-primary" id='password-generate'><i class="fa fa-key"></i>
                                
                                {{ trans('users.generate-password') }}</a>
                                @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.confirm-password') }}</label>
                            <div class="col-md-6">
                                <input type="password" class="form-control" name="password_confirmation">
                                @if ($errors->has('password_confirmation'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password_confirmation') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                <i class="fa fa-btn fa-user"></i>{{ trans('users.create') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('javascript')
<script type="text/javascript">
    $(document).ready(function() {
        var pass_field=$("#password");
            $('#password-generate').click(function(e){ //on add input button click
            e.preventDefault();
            pass_field.val(randomPassword(8));
            });
                
            function randomPassword(length) {
                var chars = "abcdefghijklmnopqrstuvwxyz!@#$%^&*()-+<>ABCDEFGHIJKLMNOP1234567890";
                var pass = "";
                for (var x = 0; x < length; x++) {
                var i = Math.floor(Math.random() * chars.length);
                pass += chars.charAt(i);
                }
                return pass;
            }
    } );
</script>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-bars"></i>
</i>
 {{ trans('users.users') }}</div>

                <div class="panel-body">
                               
                @can('create_users')
                    <a class="btn btn-primary" href="{{ url('/users/create') }}"><i class="fa fa-plus-circle"></i>
  {{ trans('users.new-user') }}</a>
                    <hr>
                @endcan
                <div class="row">
                    <div class="col-md-12">
                        <table id="promotions-table" class="display" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>{{ trans('users.id') }}</th>
                                    <th>{{ trans('users.username') }}</th>
                                    <th>{{ trans('users.email') }}</th>
                                    <th>{{ trans('users.role') }}</th>
                                    <th>{{ trans('users.cwid') }}</th>
                                    <th>{{ trans('users.phone') }}</th>
                                    <th>{{ trans('users.state') }}</th>
                                    <th>{{ trans('users.action') }}</th>
                                </tr>
                            </thead>
                            
                            <tbody>
                                 @foreach ($users as $user)
                                 	<tr>
                                 		<td>{{$user->id}}</td>
                                 		<td>{{$user->name}}</td>
                                 		<td>{{$user->email}}</td>
                                 		<td>
                                 			@foreach ($user->roles()->get() as $role)
                                 			{{$role->label}} <br>
                                 			@endforeach  
                                 		</td>
                                        <td>{{$user->cwid}}</td>
                                        <td>{{$user->phone}}</td>
                                 		<td>{{($user->is_active)?trans('users.active-yes'):trans('users.active-no')}}</td>
                                 		<td class="text-center">
                                          @can('create_users')  
                                            <a href="{{url('users').'/'.$user->id.'/edit'}}" type="button"  id='info' class="btn btn-info" aria-label="Left Align" data-product-name="1">
                                                <i class="fa fa-cog" aria-hidden="true"></i>

                                            </a>
                                            
                                            @endcan
                                        </td>
                                 	</tr>
                                 @endforeach  
                            </tbody>
                        </table>
                    </div>
                 </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            //$('#promotions-table').DataTable();

            $('#promotions-table').dataTable({
                "language": { 
    "lengthMenu": "_MENU_ "+"{{ trans('general.table-display-tail') }}",
    "zeroRecords": "{{ trans('general.table-zero-records') }}",
    "info": "{{ trans('general.table-page') }}"+" _PAGE_ "+"{{ trans('general.table-from') }}"+" _PAGES_",
    "infoEmpty": "{{ trans('general.table-zero-records') }}",
    "infoFiltered": "({{ trans('general.table-filtered-from') }} _MAX_ {{ trans('general.table-filtered-records') }})",
    "search": "{{ trans('general.search-label') }}:",
    "paginate": {
        "first":      "{{ trans('general.table-first') }}",
        "last":       "{{ trans('general.table-last') }}",
        "next":       "{{ trans('general.table-next') }}",
        "previous":   "{{ trans('general.table-previous') }}"
    },
}
            });

        } );
    </script>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">{{ trans('users.edit') }}</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ url('/users', $user['id']) }}">
                        <input type="hidden" name="_method" value="PUT">
                        {!! csrf_field() !!}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.name') }}</label>
                            <div class="col-md-6">
                                <input type="text" class="form-control" name="name" value="{{ $user['name'] }}">
                                @if ($errors->has('name'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('name') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.email') }}</label>
                            <div class="col-md-6">
                                <input type="email" class="form-control" name="email" value="{{ $user['email'] }}">
                                @if ($errors->has('email'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('email') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                         <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.phone') }}</label>
                            <div class="col-md-6">
                                <input type="phone" class="form-control" name="phone" value="{{ $user->phone }}">
                            </div>
                            </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.cwid') }}</label>
                            <div class="col-md-6">
                                <input type="cwid" class="form-control" name="cwid" value="{{ $user['cwid'] }}">
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="col-md-4 control-label">{{ trans('users.role') }}</label>
                            <div class="col-md-4">
                                <select name="role_name" class="form-control">
                                    @foreach ($roles as $role)
                                    <option {{ $user->hasRole($role->name) ? 'selected' : '' }} value="{{$role->name}}">
                                        {{$role->label}}
                                    </option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-4 control-label">{{ trans('users.state') }}</label>
                            <div class="col-md-4">
                                <div class="radio" class="form-control">
                                    <label><input type="radio" name="is_active" value="1" {{$user->is_active?'checked':''}}>{{ trans('users.active-yes') }}</label>
                                </div>
                                <div class="radio" class="form-control">
                                    <label><input type="radio" name="is_active" value="0" {{$user->is_active?'':'checked'}}>{{ trans('users.active-no') }}</label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.password') }}</label>
                            <div class="col-md-6">
                                <input type="password" class="form-control" id="password" name="password">
                                @if ($errors->has('password'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                            <label class="col-md-4 control-label">{{ trans('users.confirm-password') }}</label>
                            <div class="col-md-6">
                                <input type="password" class="form-control" name="password_confirmation">
                                @if ($errors->has('password_confirmation'))
                                <span class="help-block">
                                    <strong>{{ $errors->first('password_confirmation') }}</strong>
                                </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                <i class="fa fa-btn fa-user"></i>{{ trans('users.edit') }}
                                </button>
                            </div>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection